import { escapeHtml } from "./format.js";

export type GalleryItem = {
  name: string;
  svg: string;
};

export function buildGalleryHtml(items: GalleryItem[]): string {
  const figures = items.map((item) => {
    const stem = item.name.replace(/\.svg$/i, "");
    return `  <figure id="${escapeHtml(stem)}">
    <figcaption>${escapeHtml(item.name)}</figcaption>
${item.svg.trimEnd()}
  </figure>`;
  });
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>markvis gallery</title>
  <style>
    :root { color-scheme: light; }
    body { margin: 0; font-family: ui-sans-serif, system-ui, sans-serif; background: #f8fafc; color: #0f172a; }
    header { padding: 20px 24px 8px; }
    h1 { font-size: 20px; margin: 0 0 8px; }
    p { margin: 0; color: #475569; font-size: 14px; }
    .gallery { display: grid; grid-template-columns: repeat(auto-fill, minmax(360px, 1fr)); gap: 20px; padding: 16px 24px 32px; }
    figure { margin: 0; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; }
    figcaption { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; margin: 0 0 8px; }
    svg { max-width: 100%; height: auto; display: block; }
  </style>
</head>
<body>
  <!-- generated by markvis gallery; do not hand-edit -->
  <header>
    <h1>markvis gallery</h1>
    <p>${items.length} charts from SVG snapshots</p>
  </header>
  <div class="gallery">
${figures.join("\n")}
  </div>
</body>
</html>
`;
}
